/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

// The model
import Aston from '/3d/models/aston2.glb';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(Aston);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 84.49, 96.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object014_refl_0.geometry}
          material={materials['refl.001']}
        />
      </group>
      <group position={[0, 65.27, 175.92]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object013_lightchr_0.geometry}
          material={materials['lightchr.001']}
        />
      </group>
      <group position={[0, 84, -204.52]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object011_remit_0.geometry}
          material={materials['remit.001']}
        />
      </group>
      <group position={[0, 84, -203.13]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object010_red_0.geometry}
          material={materials.material}
        />
      </group>
      <group position={[0, 67.32, -0.74]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object009_glack_0.geometry}
          material={materials['glack.001']}
        />
      </group>
      <group position={[0, 105.73, -55.81]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object007_GLASS_0.geometry}
          material={materials['GLASS.001']}
        />
      </group>
      <group position={[0, 74.41, -9.69]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object006_LightsGlassFront_0.geometry}
          material={materials['LightsGlassFront.001']}
        />
      </group>
      <group position={[0, 61.69, -25.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object005_red2_0.geometry}
          material={materials['red2.001']}
        />
      </group>
      <group position={[0, 62.74, 187.82]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object004_xenon_0.geometry}
          material={materials['xenon.001']}
        />
      </group>
      <group position={[0, 77.71, -7.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object003_Chrome_0.geometry}
          material={materials['Chrome.003']}
        />
      </group>
      <group position={[0, 53.75, -2.62]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object002_flack_0.geometry}
          material={materials['flack.001']}
        />
      </group>
      <group position={[0, 73.11, -2.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object000_WhitePaint_0.geometry}
          material={materials['WhitePaint.001']}
        />
      </group>
      <group position={[0.04, 35.27, 204.94]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object012_grill_0.geometry}
          material={materials['grill.001']}
        />
      </group>
      <group position={[0, 110.59, -97.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.object001_BlackPaint_0.geometry}
          material={materials['BlackPaint.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(Aston);
