/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Cone(props) {
  const { nodes, materials } = useGLTF('/3d/models/cone/cone.glb');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0.geometry}
          material={materials.cono}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/3d/models/cone/cone.glb');
