/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function FoilBalloonTwo(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/3d/AdobeStock_416787733/FoilBalloonTwo.gltf',
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.foil_balloon_two.geometry}
        // material={materials.plastic_Mat}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.05, 0.05]}
      >
        <meshStandardMaterial
          // texture={materials.plastic_Mat}
          metalness={1}
          roughness={0}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/3d/AdobeStock_416787733/FoilBalloonTwo.gltf');
