/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useLoader } from '@react-three/fiber';
import { TextureLoader } from 'three/src/loaders/TextureLoader';

export default function FoilBalloonTwo(props) {
  const [colorMap, displacementMap, normalMap, roughnessMap] = useLoader(
    TextureLoader,
    [
      '/3d/AdobeStock_416787733/foil_balloon_two/plastic_Mat_baseColor.png',
      '/3d/AdobeStock_416787733/foil_balloon_two/plastic_Mat_roughness.png',
      '/3d/AdobeStock_416787733/foil_balloon_two/plastic_Mat_normal.png',
      '/3d/AdobeStock_416787733/foil_balloon_two/plastic_Mat_metallic.png',
    ],
  );
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/3d/AdobeStock_416787733/FoilBalloonTwo.gltf',
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.foil_balloon_two.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.05, 0.05]}
      >
        <meshStandardMaterial
          map={colorMap}
          displacementMap={displacementMap}
          normalMap={normalMap}
          roughnessMap={roughnessMap}
          // aoMap={aoMap}
          metalness={1}
          roughness={0}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/3d/AdobeStock_416787733/FoilBalloonTwo.gltf');
